---
title: "Analyze Clusters"
author: "Christopher Prener, Ph.D."
date: '(`r format(Sys.time(), "%B %d, %Y")`)'
output: github_document
---

```{r}
library(spdep)
library(sf)
```

```{r}
freq_respondents <- st_read(here("data", "summaries", "freq_respondents"), stringsAsFactors = FALSE) %>%
  st_transform(crs = 26915)

freq_respondents <- mutate(freq_respondents, frequent_pct = frequent/53*100)

freq_respondents <- as(freq_respondents, Class = "Spatial")
```

```{r}
nb <- poly2nb(freq_respondents, queen=FALSE)
lw <- nb2listw(nb, style="W", zero.policy=TRUE)
```

```{r}
moran.test(freq_respondents$frequent_pct,lw)
```

```{r}
moran.mc(freq_respondents$frequent_pct, lw, nsim=999)
```


```{r}
reg_respondents <- st_read(here("data", "summaries", "reg_respondents"), stringsAsFactors = FALSE) %>%
  st_transform(crs = 26915)

reg_respondents <- mutate(reg_respondents, regular_pct = regular/53*100)

reg_respondents <- as(reg_respondents, Class = "Spatial")
```

```{r}
nb <- poly2nb(reg_respondents, queen=FALSE)
lw <- nb2listw(nb, style="W", zero.policy=TRUE)
```

```{r}
moran.test(reg_respondents$regular_pct,lw)
```

```{r}
moran.mc(reg_respondents$regular_pct, lw, nsim=999)
```
