---
title: "Map Clusters"
author: "Christopher Prener, Ph.D."
date: '(`r format(Sys.time(), "%B %d, %Y")`)'
output: github_document
---

## Introduction
This notebook imports the shapefiles created by `summarize.Rmd` and maps them.

## Dependencies
This notebook requires the following packages:

```{r load-packages}
# spatial packages
library(sf)
library(tmap)

# tidyverse packages
library(dplyr)
library(ggplot2)

# other packages
library(cowplot)
library(here)
```

## Load Data
The following shapefiles with participant data are needed:

```{r load-data}
freq_clusters <- st_read(here("data", "summaries", "freq_clusters"), stringsAsFactors = FALSE) %>%
  st_transform(crs = 26915)

freq_respondents <- st_read(here("data", "summaries", "freq_respondents"), stringsAsFactors = FALSE) %>%
  st_transform(crs = 26915)

reg_clusters <- st_read(here("data", "summaries", "reg_clusters"), stringsAsFactors = FALSE) %>%
  st_transform(crs = 26915)

reg_respondents <- st_read(here("data", "summaries", "reg_respondents"), stringsAsFactors = FALSE) %>%
  st_transform(crs = 26915)

crime <- st_read(here("data", "crime", "crime_grid"), stringsAsFactors = FALSE) %>%
  st_transform(crs = 26915)
```

These additional shapefiles are also used for mapping:

```{r}
metro <- st_read(here("data", "spatial", "STL_TRANS_Metrolink"), stringsAsFactors = FALSE) %>%
  st_transform(crs = 26915)

roads <- st_read(here("data", "spatial", "STL_TRANS_PrimaryRoads"), stringsAsFactors = FALSE) %>%
  st_transform(crs = 26915)

campus <- st_read(here("data", "spatial", "ZONE_CAMPUS_SLU"), stringsAsFactors = FALSE) %>%
  st_transform(crs = 26915)
```

## Geoprocessing Data

```{r}
freq_clusters %>%
  mutate(id = 1) %>%
  group_by(id) %>%
  summarise(name = "study area") -> study_area
```

```{r}
roads <- st_crop(roads, study_area) %>%
  filter(RTTYP == "I")
```

```{r}
metro <- st_crop(metro, study_area)
```

```{r}
freq_clusters <- st_transform(freq_clusters, crs = 4269)
freq_respondents <- st_transform(freq_respondents, crs = 4269)
reg_respondents <- st_transform(reg_respondents, crs = 4269)
reg_clusters <- st_transform(reg_clusters, crs = 4269)

crime <- st_transform(crime, crs = 4269)

roads <- st_transform(roads, crs = 4269)
campus <- st_transform(campus, crs = 4269)
metro <- st_transform(metro, crs = 4269)
```

```{r}
labels <- tibble(
  name = c("North Campus", "South Campus"),
  x = c(-90.235964, -90.236005),
  y = c(38.639756, 38.620040)
)

labels <- st_as_sf(labels, coords = c("x", "y"), crs = 4269)
```

```{r}
nhood <- tibble(
  name = c("Central West End", "Grand Center", "Forest Park Southeast"),
  x = c(-90.255050, -90.232176, -90.256972),
  y = c(38.641675, 38.642287, 38.626802)
)

nhood <- st_as_sf(nhood, coords = c("x", "y"), crs = 4269)

```

```{r}
features <- tibble(
  name = c("I-44", "I-64", "Metro"),
  x = c(-90.268058, -90.268058, -90.265650),
  y = c(38.616898, 38.628251, 38.642927)
)

features <- st_as_sf(features, coords = c("x", "y"), crs = 4269)

```


```{r}

tm_shape(freq_clusters) +
    tm_polygons(title = "Count of Clusters", col = "frequent", style = "jenks") +
  tm_shape(roads) +
    tm_lines(lwd = 1.5, col = "#474747") +
  tm_shape(metro) +
    tm_lines() +
  tm_shape(campus) +
    tm_borders(lwd = 2, col = "#000000") +
  tm_shape(labels) +
    tm_text("name", fontface = 2, just = "left", size = 1, shadow = TRUE) +
  tm_shape(nhood) +
    tm_text("name", fontface = 4, size = .75, shadow = TRUE) +
  tm_shape(features) +
    tm_text("name", fontface = 3, just = "bottom", size = .75, shadow = TRUE) +
  tm_layout(title = "Frequent Visits \nby Cluster",
            frame = FALSE, outer.margins = c(0, 0, 0, 0)) +
  tm_scale_bar(position=c("right", "bottom"), just = "top") +
  tm_legend(outside = TRUE, attr.outside = TRUE) -> freq_clusters_map

tmap_save(tm = freq_clusters_map, filename = here("results", "freq_clusters_map.png"), dpi = 500)
```

```{r}
freq_respondents <- mutate(freq_respondents, frequent_pct = frequent/53*100)

breaks <- c(0, 8, 16.5, 33, 66, 100)

tm_shape(freq_respondents) +
    tm_polygons(title = "% of Respondents", col = "frequent_pct", 
                breaks = breaks, palette = "Blues") +
  tm_shape(roads) +
    tm_lines(lwd = 1.5, col = "#474747") +
  tm_shape(metro) +
    tm_lines() +
  tm_shape(campus) +
    tm_borders(lwd = 2, col = "#000000") +
  tm_shape(labels) +
    tm_text("name", fontface = 2, just = "left", size = 1, shadow = TRUE) +
  tm_shape(nhood) +
    tm_text("name", fontface = 4, size = .75, shadow = TRUE) +
  tm_shape(features) +
    tm_text("name", fontface = 3, just = "bottom", size = .75, shadow = TRUE) +
  tm_layout(title = "Frequent Visits \nby Respondent",
            frame = FALSE, outer.margins = c(0,0,0,0)) +
  tm_scale_bar(position=c("right", "bottom"), just = "top") +
  tm_legend(outside = TRUE, attr.outside = TRUE) -> freq_respondents_map

tmap_save(tm = freq_respondents_map, filename = here("results", "freq_respondents_map.png"), dpi = 500)
```

```{r}
freq_respondents <- mutate(freq_respondents, frequent_pct = frequent/53*100)

breaks <- c(0, 8, 16.5, 33, 66, 100)

tm_shape(freq_respondents) +
    tm_polygons(title = "% of Respondents", col = "frequent_pct", 
                breaks = breaks, palette = "Blues") +
  tm_shape(roads) +
    tm_lines(lwd = 1.5, col = "#474747") +
  tm_shape(metro) +
    tm_lines() +
  tm_shape(campus) +
    tm_borders(lwd = 2, col = "#000000") +
  tm_shape(labels) +
    tm_text("name", fontface = 2, just = "left", size = 1, shadow = TRUE) +
  tm_shape(nhood) +
    tm_text("name", fontface = 4, size = .75, shadow = TRUE) +
  tm_shape(features) +
    tm_text("name", fontface = 3, just = "bottom", size = .75, shadow = TRUE) +
  tm_layout(frame = FALSE, outer.margins = c(0,0,0,0)) +
  tm_scale_bar(position=c("right", "bottom"), just = "top") +
  tm_legend(outside = TRUE, attr.outside = TRUE) -> freq_respondents_map

tmap_save(tm = freq_respondents_map, filename = here("results", "figure4.png"), dpi = 500)
```

```{r}

tm_shape(reg_clusters) +
    tm_polygons(title = "Count of Clusters", col = "regular", 
                style = "jenks", palette = "Reds") +
  tm_shape(roads) +
    tm_lines(lwd = 1.5, col = "#474747") +
  tm_shape(metro) +
    tm_lines() +
  tm_shape(campus) +
    tm_borders(lwd = 2, col = "#000000") +
  tm_shape(labels) +
    tm_text("name", fontface = 2, just = "left", size = 1, shadow = TRUE) +
  tm_shape(nhood) +
    tm_text("name", fontface = 4, size = .75, shadow = TRUE) +
  tm_shape(features) +
    tm_text("name", fontface = 3, just = "bottom", size = .75, shadow = TRUE) +
  tm_layout(title = "Regular Visits \nby Cluster",
            frame = FALSE, outer.margins = c(0,0,0,0)) +
  tm_scale_bar(position=c("right", "bottom"), just = "top") +
  tm_legend(outside = TRUE, attr.outside = TRUE) -> reg_clusters_map

tmap_save(tm = reg_clusters_map, filename = here("results", "reg_clusters_map.png"), dpi = 500)
```

```{r}
reg_respondents <- mutate(reg_respondents, regular_pct = regular/53*100)

breaks <- c(0, 8, 16.5, 33, 49.5, 66)

tm_shape(reg_respondents) +
    tm_polygons(title = "% of Respondents", col = "regular_pct", 
                breaks = breaks, palette = "Greens") +
  tm_shape(roads) +
    tm_lines(lwd = 1.5, col = "#474747") +
  tm_shape(metro) +
    tm_lines() +
  tm_shape(campus) +
    tm_borders(lwd = 2, col = "#000000") +
  tm_shape(labels) +
    tm_text("name", fontface = 2, just = "left", size = 1, shadow = TRUE) +
  tm_shape(nhood) +
    tm_text("name", fontface = 4, size = .75, shadow = TRUE) +
  tm_shape(features) +
    tm_text("name", fontface = 3, just = "bottom", size = .75, shadow = TRUE) +
  tm_layout(title = "Regular Visits \nby % of Respondents",
            frame = FALSE, outer.margins = c(0,0,0,0)) +
  tm_scale_bar(position=c("right", "bottom"), just = "top") +
  tm_legend(outside = TRUE, attr.outside = TRUE) -> reg_respondents_map

tmap_save(tm = reg_respondents_map, filename = here("results", "reg_respondents_map.png"), dpi = 500)
```

```{r}
reg_respondents <- mutate(reg_respondents, regular_pct = regular/53*100)

breaks <- c(0, 8, 16.5, 33, 49.5, 66)

tm_shape(reg_respondents) +
    tm_polygons(title = "% of Respondents", col = "regular_pct", 
                breaks = breaks, palette = "Greens") +
  tm_shape(roads) +
    tm_lines(lwd = 1.5, col = "#474747") +
  tm_shape(metro) +
    tm_lines() +
  tm_shape(campus) +
    tm_borders(lwd = 2, col = "#000000") +
  tm_shape(labels) +
    tm_text("name", fontface = 2, just = "left", size = 1, shadow = TRUE) +
  tm_shape(nhood) +
    tm_text("name", fontface = 4, size = .75, shadow = TRUE) +
  tm_shape(features) +
    tm_text("name", fontface = 3, just = "bottom", size = .75, shadow = TRUE) +
  tm_layout(frame = FALSE, outer.margins = c(0,0,0,0)) +
  tm_scale_bar(position=c("right", "bottom"), just = "top") +
  tm_legend(outside = TRUE, attr.outside = TRUE) -> reg_respondents_map

tmap_save(tm = reg_respondents_map, filename = here("results", "figure5.png"), dpi = 500)
```

```{r}
# reg_respondents <- mutate(reg_respondents, regular_pct = regular/53*100)

# breaks <- c(0, 8, 16.5, 33, 49.5, 66)

tm_shape(crime) +
    tm_polygons(title = "Property Crime Rates\nper 1,000 Estimated Residents", col = "prprty_", 
                style = "jenks", palette = "BuGn") +
  tm_shape(roads) +
    tm_lines(lwd = 1.5, col = "#474747") +
  tm_shape(metro) +
    tm_lines() +
  tm_shape(campus) +
    tm_borders(lwd = 2, col = "#000000") +
  tm_shape(labels) +
    tm_text("name", fontface = 2, just = "left", size = 1, shadow = TRUE) +
  tm_shape(nhood) +
    tm_text("name", fontface = 4, size = .75, shadow = TRUE) +
  tm_shape(features) +
    tm_text("name", fontface = 3, just = "bottom", size = .75, shadow = TRUE) +
  tm_layout(frame = FALSE, outer.margins = c(0,0,0,0)) +
  tm_scale_bar(position=c("right", "bottom"), just = "top") +
  tm_legend(outside = TRUE, attr.outside = TRUE) -> property_map

tmap_save(tm = property_map, filename = here("results", "property_map.png"), dpi = 500)
```

```{r}
# reg_respondents <- mutate(reg_respondents, regular_pct = regular/53*100)

# breaks <- c(0, 8, 16.5, 33, 49.5, 66)

tm_shape(crime) +
    tm_polygons(title = "Violent Crime Rates\nper 1,000 Estimated Residents", col = "vlnt_rt", 
                style = "jenks", palette = "BuGn") +
  tm_shape(roads) +
    tm_lines(lwd = 1.5, col = "#474747") +
  tm_shape(metro) +
    tm_lines() +
  tm_shape(campus) +
    tm_borders(lwd = 2, col = "#000000") +
  tm_shape(labels) +
    tm_text("name", fontface = 2, just = "left", size = 1, shadow = TRUE) +
  tm_shape(nhood) +
    tm_text("name", fontface = 4, size = .75, shadow = TRUE) +
  tm_shape(features) +
    tm_text("name", fontface = 3, just = "bottom", size = .75, shadow = TRUE) +
  tm_layout(frame = FALSE, outer.margins = c(0,0,0,0)) +
  tm_scale_bar(position=c("right", "bottom"), just = "top") +
  tm_legend(outside = TRUE, attr.outside = TRUE) -> violent_map

tmap_save(tm = violent_map, filename = here("results", "violent_map.png"), dpi = 500)
```


```{r}
st_geometry(freq_respondents) <- NULL
st_geometry(reg_respondents) <- NULL
```


```{r}
crime_freq <- left_join(crime, freq_respondents, by = "GRID_ID")

ggplot(data = crime_freq, mapping = aes(prprty_, frequent)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
ggplot(data = crime_freq, mapping = aes(vlnt_rt, frequent)) +
  geom_point() +
  geom_smooth(method = "lm")
```


```{r}
ggplot(data = crime_freq, mapping = aes(prt1_rt, frequent/100)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(
    title = "Frequent Visits by % of Respondents",
    x = "",
    y = "% of Frequent Visits"
  ) +
  scale_y_continuous(labels = scales::percent, limits = c(0, .6)) -> a
  
```

```{r}
crime_reg <- left_join(crime, reg_respondents, by = "GRID_ID")

ggplot(data = crime_reg, mapping = aes(prt1_rt, regular/100)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(
    title = "Regular Visits by % of Respondents",
    x = "Part 1 Crime Rate (per 1,000 estimated residents)",
    y = "% of Regular Visits"
  ) +
  scale_y_continuous(labels = scales::percent, limits = c(0, .6)) -> b
```

```{r}
c <- plot_grid(a, b, labels = c('A', 'B'), ncol = 1, align = "v")

ggsave(filename = here("results", "rate_plots.png"), dpi = 500, units = "in", width = 8, height = 5 )
```

